name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.6]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        python hellow.py test
    - name: Merge Branch
      run: |
        git config --global user.email "901akhil@gmail.com"
        git config --global user.name "avvaruakhil"
        git clone "https://github.com/avvaruakhil/demo.git"
        git config pull.rebase false
        git fetch
        git checkout main
        git pull
        git push
        git checkout testing
        git pull origin main --allow-unrelated-histories
        git mergetool
        git push
        git merge main
        #git commit -I "a commit by github actions on develop"
        #git push
